import { useState } from 'react'

export function App() {
  const [currentPage, setCurrentPage] = useState('home')

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      <div className="container mx-auto p-4">
        <header className="mb-8">
          <h1 className="text-3xl font-bold mb-4">Orchids UI</h1>
          <nav className="flex gap-4">
            <button
              onClick={() => setCurrentPage('home')}
              className={`px-4 py-2 rounded ${
                currentPage === 'home'
                  ? 'bg-blue-500'
                  : 'bg-gray-800 hover:bg-gray-700'
              }`}
            >
              Home
            </button>
            <button
              onClick={() => setCurrentPage('dashboard')}
              className={`px-4 py-2 rounded ${
                currentPage === 'dashboard'
                  ? 'bg-blue-500'
                  : 'bg-gray-800 hover:bg-gray-700'
              }`}
            >
              Dashboard
            </button>
            <button
              onClick={() => setCurrentPage('settings')}
              className={`px-4 py-2 rounded ${
                currentPage === 'settings'
                  ? 'bg-blue-500'
                  : 'bg-gray-800 hover:bg-gray-700'
              }`}
            >
              Settings
            </button>
          </nav>
        </header>

        <main>
          {currentPage === 'home' && (
            <section className="bg-[#1a1a1a] p-8 rounded border border-[#252525]">
              <h2 className="text-2xl font-bold mb-4">Welcome to Orchids UI</h2>
              <p className="text-gray-300">
                Components generated by Stitch and Jules will be loaded here.
              </p>
            </section>
          )}

          {currentPage === 'dashboard' && (
            <section className="bg-[#1a1a1a] p-8 rounded border border-[#252525]">
              <h2 className="text-2xl font-bold mb-4">Dashboard</h2>
              <p className="text-gray-300">Dashboard components coming soon.</p>
            </section>
          )}

          {currentPage === 'settings' && (
            <section className="bg-[#1a1a1a] p-8 rounded border border-[#252525]">
              <h2 className="text-2xl font-bold mb-4">Settings</h2>
              <p className="text-gray-300">Settings components coming soon.</p>
            </section>
          )}
        </main>
      </div>
    </div>
  )
}
